language: go

os: linux
dist: xenial

go:
  - "1.13"
  - "1.14"
  - "1.15"
  - "1.16"
  - tip

before_install:
  - go get -t -v ./...

script:
  - sh coverage.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
